spring.datasource:
        url: jdbc:${CLEARDB_PUCE_URL:mysql://localhost:3306/blog}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
server.port: ${PORT:8080}
spring.jpa:
        hibernate.ddl-auto: none
        show-sql: false
        properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

spring.liquibase:
        enabled: false
        change-log: classpath:/db/changelog/db.changelog-master.xml

blog:
        title: DevPub
        subtitle: Рассказы разработчиков
        phone: +7 903 666-44-55
        copyright: Дмитрий Сергеев
        copyrightFrom: 2005

#время устаревания капчи и ссылки на смену пароля в минутах
        captcha.expire: 10

#время устаревания ссылки на смену пароля в минутах
        restore.code.expire: 10

#глобальные параметры блога
        multiUserMode: true
        postPremoderation: true
        statisticIsPublic: true

#путь и максимальный размер загружаемой фотографии пользователя
        image.upload:
                path: upload
                maxfilesize: 5242880

#максимальный размер загружаемого файла,
spring.servlet.multipart.max-file-size: 20MB
spring.servlet.multipart.max-request-size: 20MB

#параметры почтового сервера
spring.mail:
        host: smtp.gmail.com
        port: 587
        username: padre.mets@gmail.com
        password: ulnrhkulkvawzixh
        properties.mail.smtp.auth: true
        properties.mail.smtp.starttls.enable: true